# Generated by Django 4.2.7 on 2023-12-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("passenger", "0004_remove_passenger_users"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="passengers",
            field=models.ManyToManyField(to="passenger.passenger"),
        ),
    ]
