# Generated by Django 4.2.7 on 2023-12-16 19:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_passengers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="passengers",
        ),
    ]
