# Generated by Django 4.2.7 on 2023-11-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passenger', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='passengers',
            field=models.ManyToManyField(to='passenger.passenger'),
        ),
    ]
