# Generated by Django 4.2.7 on 2023-12-19 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("order", "0003_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="flight_id",
            new_name="flight",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user_id",
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
