# Generated by Django 4.2.7 on 2023-11-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_from', models.CharField(max_length=100)),
                ('city_to', models.CharField(max_length=100)),
                ('airport_from', models.CharField(max_length=100)),
                ('airport_to', models.CharField(max_length=100)),
                ('time_from', models.DateTimeField()),
                ('time_to', models.DateTimeField()),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('time_in_flight', models.IntegerField(default=0)),
                ('flight_sum', models.IntegerField(default=0)),
                ('luggage', models.IntegerField(default=0)),
                ('hand_laggage', models.IntegerField(default=0)),
                ('refund', models.CharField(max_length=100)),
            ],
        ),
    ]
