# Generated by Django 4.2.7 on 2023-12-16 20:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flight", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flight",
            name="time_from",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="time_to",
        ),
    ]
