# Generated by Django 4.2.7 on 2023-12-17 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flight", "0003_flight_passengers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flight",
            old_name="passengers",
            new_name="seats",
        ),
    ]
