version: '3.9'

services:
  frontend:
    container_name: frontend
    image: goluballa/frontend
    networks:
      aerotravel:
    ports: 
      - 80:80
    volumes:
      - ./frontend:/frontend
  
  backend:
    container_name: backend
    image: goluballa/backend
    networks:
      aerotravel:
    ports: 
      - 8000:8000
    volumes:
      - ./back:/backend

networks:
  aerotravel:
    external: true